//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekiemtra_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyHoc
    {
        public int MaDangKy { get; set; }
        public string MaSV { get; set; }
        public string MaMon { get; set; }
        public string NamHocKy { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
