// <auto-generated />
namespace Bai3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DateCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202012171346242_DateCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
