//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cau1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int MaSV { get; set; }
        public Nullable<int> MaCB { get; set; }
        public Nullable<int> MaMon { get; set; }
        public string HoTenSV { get; set; }
    
        public virtual CanBo CanBo { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
