//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cau1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loaithietbi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loaithietbi()
        {
            this.Thietbis = new HashSet<Thietbi>();
        }
    
        public int Maloai { get; set; }
        public string Tenloai { get; set; }
        public string Danhmuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thietbi> Thietbis { get; set; }
    }
}
