//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cauu2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thietbi
    {
        public int MaTB { get; set; }
        public Nullable<int> MaDV { get; set; }
        public Nullable<int> Maloai { get; set; }
        public string TenTB { get; set; }
        public string NuocXB { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual Loaithietbi Loaithietbi { get; set; }
    }
}
