//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cau2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyHoc
    {
        public int MaDK { get; set; }
        public int MaSV { get; set; }
        public int MaMon { get; set; }
        public string NamHK { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
